// 架构图谱的数据源。
//
// 现在（第 0 阶段之前）：手工维护，和 docs/architecture.md、docs/design.md 保持一致。
// 以后：由 `npm run atlas:export` 从代码里的模块注册表自动导出 status = 'done' 的部分，
//       还没实现的条目继续留在这里（status = 'draft' / 'wip'）。
// 每次改完：`npm run atlas` = 校验（引用完整、命令例子都能解析）+ 生成 docs/atlas.html。
//
// status: 'draft' 草案 | 'wip' 开发中 | 'done' 已实现
globalThis.ATLAS = {
  meta: {
    title: '诸侯争霸 · 架构图谱',
    subtitle: 'AI 诸侯只做战略决策，成百上千的职业 NPC 自己干活',
    version: '0.1-draft',
    updated: '2026-10-04',
    source: '设计草案（docs/architecture.md、docs/design.md）',
  },

  // ------------------------------------------------------------------ 原则
  principles: [
    { icon: '🧩', title: '一个功能 = 一个模块', text: '模块向核心登记自己的命令、简报、存档、配置、画面图层；加功能不改核心文件。' },
    { icon: '📜', title: '命令只定义一次', text: '解析器、AI 命令表、上帝面板按钮、文档、测试，全部从同一份定义生成。' },
    { icon: '🎯', title: 'AI 只做战略', text: 'NPC 按行为自己干活；AI 给群体下长期命令，一个季节决策几次。' },
    { icon: '⚖️', title: '规则只有一个入口', text: '所有对世界的改动都走"动作"：NPC、AI、上帝、测试用同一套规则。' },
    { icon: '🌫️', title: '迷雾第一天就有', text: '每个势力一份情报库；AI 简报只读情报，不读真实数据，撒谎才有意义。' },
    { icon: '⚡', title: '按大规模来写', text: '数据按紧凑数组存、固定节拍、远处粗算；压测超预算就算测试失败。' },
  ],

  // ------------------------------------------------------------------ 分层
  layers: [
    { id: 'client', name: '前端', en: 'client', color: '#f472b6', deps: ['protocol', 'shared'],
      role: '浏览器：画面图层、界面面板、镜头、输入 → 命令。只依赖通信格式，绝不碰模拟代码。',
      dirs: ['src/client/'], items: ['main.ts', 'net.ts', 'camera.ts', 'layers/', 'panels/'], status: 'draft' },
    { id: 'protocol', name: '通信格式', en: 'protocol', color: '#e879f9', deps: ['shared'], side: true,
      role: 'WebSocket 消息格式，前后端共用同一份类型：改了一边，另一边编译就报错。',
      dirs: ['src/protocol/'], items: ['messages.ts', 'codec/'], status: 'draft' },
    { id: 'server', name: '宿主', en: 'server', color: '#fb923c', deps: ['ai', 'game', 'engine', 'protocol', 'shared'],
      role: '主循环、WebSocket 网关、视野订阅、存档文件、管理接口（改配置、存读档、时间倍率）。',
      dirs: ['src/server/'], items: ['main.ts', 'loop.ts', 'gateway.ts', 'interest.ts', 'persistence.ts', 'admin.ts'], status: 'draft' },
    { id: 'ai', name: 'AI 席位', en: 'ai', color: '#facc15', deps: ['game', 'engine', 'shared'],
      role: '唤醒 → 拼装简报 → 调用模型（异步，不卡模拟）→ 逐行解析 → 命令总线；全程写日志。',
      dirs: ['src/ai/'], items: ['seat.ts', 'wake.ts', 'briefing.ts', 'parser.ts', 'providers/', 'prompts/'], status: 'draft' },
    { id: 'game', name: '玩法模块', en: 'game', color: '#4ade80', deps: ['engine', 'shared', 'content'],
      role: '每个玩法一个文件夹（world / economy / jobs / military …），通过模块契约向内核登记。',
      dirs: ['src/game/modules/', 'src/game/index.ts'], items: ['模块清单：加模块 = index.ts 加一行'], status: 'draft' },
    { id: 'engine', name: '通用内核', en: 'engine', color: '#38bdf8', deps: ['shared'],
      role: '实体与组件、调度、事件、命令总线、模块注册、空间索引、寻路、存档框架、远近模拟、情报库。不知道"木头"是什么。',
      dirs: ['src/engine/'], items: ['ecs/', 'scheduler.ts', 'events.ts', 'commands/', 'registry.ts', 'spatial/', 'path/', 'save.ts', 'lod.ts', 'intel.ts', 'clock.ts'], status: 'draft' },
    { id: 'shared', name: '基础', en: 'shared', color: '#a78bfa', deps: [],
      role: '类型、可重现随机数、数学、ID。谁都能用，它不依赖任何人。',
      dirs: ['src/shared/'], items: ['types.ts', 'rng.ts', 'math.ts', 'ids.ts'], status: 'draft' },
    { id: 'content', name: '内容数据', en: 'content', color: '#94a3b8', deps: ['shared'], side: true,
      role: '纯数据，没有逻辑：职业、物品、建筑、地形。加一个职业通常只加一份数据。',
      dirs: ['content/'], items: ['professions/', 'items/', 'buildings/', 'terrain/'], status: 'draft' },
  ],

  // ------------------------------------------------------------------ 模块契约
  contract: [
    { field: 'id', type: 'string', desc: '模块 ID，如 jobs' },
    { field: 'requires', type: 'string[]', desc: '依赖的模块；注册表据此排序，缺了直接报错' },
    { field: 'components', type: 'ComponentDef[]', desc: '新的数据列（组件）' },
    { field: 'systems', type: 'SystemDef[]', desc: '每节拍要跑的逻辑，声明阶段和频率' },
    { field: 'actions', type: 'ActionDef[]', desc: '改世界的规则（唯一入口），返回 { ok, reason }' },
    { field: 'orders', type: 'OrderDef[]', desc: '群体可接受的长期命令类型' },
    { field: 'behaviors', type: 'BehaviorDef[]', desc: 'NPC 能做的行为（fits / start / tick / coarse）' },
    { field: 'commands', type: 'CommandDef[]', desc: 'AI / 上帝 / 界面可用的命令（带参数格式和例子）' },
    { field: 'events', type: 'EventDef[]', desc: '会发出的事件（带可见范围）' },
    { field: 'briefing', type: 'BriefingSection[]', desc: '往 AI 简报里贡献的段落（优先级 + 长度预算）' },
    { field: 'wake', type: 'WakeRule[]', desc: '哪些事件会叫醒 AI' },
    { field: 'views', type: 'ViewChannel[]', desc: '往前端推的数据通道；前端有同名图层' },
    { field: 'content', type: 'ContentSchema[]', desc: '本模块认识的数据类型（如"职业"）' },
    { field: 'config', type: 'ConfigSchema', desc: '可调参数（默认值 + 校验）' },
    { field: 'save', type: 'SaveHandler', desc: '存档段 + 版本迁移' },
    { field: 'install', type: '(api) => void', desc: '兜底：订阅事件、查别的模块公开接口' },
  ],

  // ------------------------------------------------------------------ 节拍
  tick: {
    hz: 10,
    phases: [
      { id: 'commands', name: '收命令', text: '本拍之前到达的命令按顺序校验、执行（AI、上帝、界面、测试都一样）' },
      { id: 'input', name: 'input', text: '外部输入、上帝干预落地' },
      { id: 'ai_npc', name: 'ai_npc', text: 'NPC 空闲时按长期命令和职业挑行为' },
      { id: 'act', name: 'act', text: '行为调用动作：采集、投料、攻击……' },
      { id: 'move', name: 'move', text: '移动、寻路（每拍有计算预算）' },
      { id: 'resolve', name: 'resolve', text: '战斗结算、产出到账' },
      { id: 'economy', name: 'economy', text: '仓库、国库、物流' },
      { id: 'population', name: 'population', text: '吃饭、民心、增长、迁移（多为每游戏日一次）' },
      { id: 'post', name: 'post', text: '统计、史册' },
      { id: 'events', name: '派发事件', text: '本拍事件发给订阅者：史册、AI 唤醒、前端通知、其他模块' },
      { id: 'push', name: '推送', text: '按每个网页的视野推送变化' },
    ],
  },

  // ------------------------------------------------------------------ 模块
  modules: [
    { id: 'world', name: '世界', icon: '🗺️', requires: [], stage: 0, status: 'draft',
      summary: '两层地图：地区图（战略）+ 按需生成的 2 米格子区块；资源点、懒刷新、季节。',
      systems: ['区块加载/卸载', '资源懒刷新', '季节推进'], actions: ['harvestTile', 'till', 'sow', 'reap', 'alterTile'],
      events: ['season.changed', 'resource.depleted', 'region.discovered'],
      briefing: ['地区与资源'], views: ['terrain', 'resources', 'regions'],
      config: ['地图种子', '地图边长 10km', '刷新速率'], save: '种子 + 改动过的格子' },
    { id: 'economy', name: '经济', icon: '💰', requires: ['world'], stage: 1, status: 'draft',
      summary: '物品、仓库、国库、搬运。',
      components: ['Carry'], systems: ['库存账本'], actions: ['deposit', 'withdraw', 'transfer'],
      events: ['stock.low'], briefing: ['国库'], views: ['stock'], content: ['items'],
      config: ['物品定义'], save: '各仓库库存' },
    { id: 'population', name: '人口', icon: '👥', requires: ['economy'], stage: 1, status: 'draft',
      summary: '吃饭（城镇层面结算）、民心、增长、迁移、名人。',
      components: ['Identity', 'Vitals', 'Notable'], systems: ['每日口粮', '民心', '人口增长', '迁移'],
      events: ['npc.born', 'npc.died', 'npc.migrated', 'settlement.starving', 'notable.defected'],
      wake: ['settlement.starving', 'notable.defected'], briefing: ['城镇人口与民心'], views: ['settlements'],
      config: ['口粮', '迁移阈值'], save: '城镇、名人' },
    { id: 'jobs', name: '职业', icon: '🛠️', requires: ['world', 'economy', 'population'], stage: 1, status: 'draft',
      summary: '职业数据、工作行为、职业比例自动分配、锁定与转职、编组。',
      components: ['Profession'], orders: ['work', 'haul', 'idle'], actions: ['craft'],
      systems: ['比例分配', '转职'], events: ['npc.retrained'], briefing: ['劳力分配'], views: ['units'],
      content: ['professions'], config: ['转职耗时'], save: '比例设置、编组' },
    { id: 'building', name: '建造', icon: '🏗️', requires: ['world', 'economy', 'jobs'], stage: 1, status: 'draft',
      summary: '建筑与施工：诸侯只说造什么，建筑工自己搬料施工。',
      orders: ['build'], actions: ['placeSite', 'contribute', 'demolish'],
      events: ['building.done', 'building.destroyed'], briefing: ['工程'], views: ['buildings'],
      content: ['buildings'], save: '建筑与工地' },
    { id: 'military', name: '军事', icon: '⚔️', requires: ['world', 'population', 'jobs'], stage: 2, status: 'draft',
      summary: '编队、行军、围城、战斗（远处公式结算，观看时逐个模拟）。',
      components: ['Combat', 'Equipment'], orders: ['guard', 'patrol', 'move', 'attack', 'escort', 'scout'],
      systems: ['战斗结算', '围城', '补给'], actions: ['attack', 'capture', 'observe'],
      events: ['battle.started', 'battle.ended', 'settlement.besieged', 'settlement.captured'],
      wake: ['settlement.besieged', 'battle.ended', 'settlement.captured'], briefing: ['军队', '敌情'],
      views: ['armies', 'battles'], save: '部队' },
    { id: 'diplomacy', name: '外交', icon: '🤝', requires: ['population'], stage: 4, status: 'draft',
      summary: '私信、公开宣告、条约（不强制执行）、声望、送礼、贸易。',
      orders: ['trade'], actions: ['exchange'], events: ['message.received', 'treaty.proposed', 'treaty.signed', 'treaty.broken'],
      wake: ['message.received', 'treaty.proposed', 'treaty.broken'], briefing: ['来信', '条约与声望'],
      save: '条约、声望、信件' },
    { id: 'chronicle', name: '史册', icon: '📜', requires: [], stage: 4, status: 'draft',
      summary: '订阅所有事件，自动编年；按情报可见范围给各方看。',
      systems: ['记录事件'], briefing: ['近事'], views: ['chronicle'], save: '史册' },
    { id: 'god', name: '上帝', icon: '☁️', requires: ['world', 'economy', 'population', 'diplomacy', 'military'], stage: 5, status: 'draft',
      summary: '天灾、天降、冒名信、托梦、召唤流寇、时间倍率。诸侯只看得到后果。',
      events: ['god.intervened'], views: ['god'], save: '干预记录' },
  ],

  // ------------------------------------------------------------------ NPC 组件
  components: [
    { id: 'Identity', name: '身份', owner: 'population', base: true, fields: [['name', 'string', '名字'], ['faction', 'id', '势力'], ['home', 'id', '所属城镇']] },
    { id: 'Transform', name: '位置', owner: 'engine', base: true, fields: [['x', 'f32', '米'], ['y', 'f32', '米'], ['region', 'u16', '所在地区']] },
    { id: 'Motion', name: '移动', owner: 'engine', base: true, fields: [['speed', 'f32', '米/秒'], ['path', 'handle', '路径'], ['target', 'vec2', '目标点']] },
    { id: 'Vitals', name: '血量', owner: 'population', base: true, fields: [['hp', 'f32', '当前'], ['maxHp', 'f32', '上限']] },
    { id: 'Carry', name: '携带', owner: 'economy', base: true, fields: [['item', 'u16', '物品种类（只拿一种）'], ['qty', 'u16', '数量'], ['cap', 'u16', '上限']] },
    { id: 'Profession', name: '职业', owner: 'jobs', base: true, fields: [['prof', 'u16', '职业 ID'], ['skill', 'u8', '熟练度']] },
    { id: 'Brain', name: '大脑', owner: 'engine', base: true, fields: [['behavior', 'u16', '当前行为'], ['state', 'blob', '行为状态'], ['order', 'id', '所属长期命令（编组共用）']] },
    { id: 'Membership', name: '编组', owner: 'engine', base: true, fields: [['groups', 'id[]', '所在编组'], ['pinned', 'bool', '是否锁定（直接派出的人）']] },
    { id: 'Lod', name: '远近', owner: 'engine', base: true, fields: [['mode', 'enum', '细算 / 粗算']] },
    { id: 'Combat', name: '战斗', owner: 'military', base: false, fields: [['attack', 'f32', '攻击'], ['defense', 'f32', '防御'], ['range', 'f32', '射程']] },
    { id: 'Equipment', name: '装备', owner: 'military', base: false, fields: [['weapon', 'u8', '兵器等级'], ['armor', 'u8', '护甲等级']] },
    { id: 'Notable', name: '名人', owner: 'population', base: false, fields: [['traits', 'string[]', '性格'], ['loyalty', 'u8', '忠诚'], ['ambition', 'string', '野心']] },
  ],

  // ------------------------------------------------------------------ 长期命令
  orders: [
    { id: 'work', name: '干活', module: 'jobs', params: ['resource', 'area?'], text: '采集或生产某种资源' },
    { id: 'haul', name: '搬运', module: 'jobs', params: ['item', 'from', 'to'], text: '在两地之间运东西' },
    { id: 'build', name: '施工', module: 'building', params: ['site'], text: '去工地搬料施工' },
    { id: 'guard', name: '驻守', module: 'military', params: ['place'], text: '守住某地，敌人进入就打' },
    { id: 'patrol', name: '巡逻', module: 'military', params: ['area'], text: '在区域里来回巡视' },
    { id: 'move', name: '行军', module: 'military', params: ['place'], text: '移动到某地' },
    { id: 'attack', name: '进攻', module: 'military', params: ['target'], text: '进攻城镇、部队或地区' },
    { id: 'escort', name: '护送', module: 'military', params: ['who'], text: '跟随并保护某人或某队' },
    { id: 'scout', name: '侦察', module: 'military', params: ['area'], text: '去某地看情况，写进情报库' },
    { id: 'trade', name: '通商', module: 'diplomacy', params: ['partner'], text: '带货去别的势力交易' },
    { id: 'idle', name: '待命', module: 'jobs', params: [], text: '原地待命' },
  ],

  // ------------------------------------------------------------------ 行为
  behaviors: [
    { id: 'gather', acts: ['moveTo', 'harvestTile'], name: '采集', module: 'jobs', fits: ['work'], coarse: true, loop: ['走到资源点', '读条采集', '拿满'], text: '采木头、石头、铁矿' },
    { id: 'farm', acts: ['moveTo', 'till', 'sow', 'reap'], name: '耕种', module: 'jobs', fits: ['work'], coarse: true, loop: ['开垦', '播种', '收割'], text: '春种秋收，冬天歇' },
    { id: 'deliver', acts: ['moveTo', 'deposit'], name: '送回', module: 'jobs', fits: [], support: true, coarse: true, loop: ['走回仓库', '卸货'], text: '辅助行为：拿满了送回最近的仓库（采集、耕种之后自动接上，不单独完成命令）' },
    { id: 'craft', acts: ['withdraw', 'craft', 'deposit'], name: '打造', module: 'jobs', fits: ['work'], coarse: true, loop: ['取料', '打造', '入库'], text: '打兵器、工具' },
    { id: 'haul', acts: ['withdraw', 'moveTo', 'deposit'], name: '搬运', module: 'jobs', fits: ['haul'], coarse: true, loop: ['去取货', '运送', '卸货'], text: '两地运货' },
    { id: 'build', acts: ['withdraw', 'moveTo', 'contribute'], name: '施工', module: 'building', fits: ['build'], coarse: true, loop: ['取木石', '走到工地', '投料施工'], text: '把料投进工地' },
    { id: 'fight', acts: ['moveTo', 'attack'], name: '战斗', module: 'military', fits: ['attack', 'guard', 'escort', 'patrol'], coarse: true, loop: ['锁定敌人', '接近', '攻击'], text: '看见敌人就打' },
    { id: 'guard', acts: ['moveTo', 'wait'], name: '站岗', module: 'military', fits: ['guard'], coarse: true, loop: ['站位', '警戒'], text: '守在指定位置' },
    { id: 'patrol', acts: ['moveTo'], name: '巡逻', module: 'military', fits: ['patrol'], coarse: true, loop: ['走向巡逻点', '换下一个点'], text: '区域内来回走' },
    { id: 'march', acts: ['moveTo'], name: '行军', module: 'military', fits: ['move'], coarse: true, loop: ['沿地区图走', '到达'], text: '远途移动（进攻、侦察时由对应行为调用）' },
    { id: 'escort', acts: ['moveTo', 'attack'], name: '随行', module: 'military', fits: ['escort'], coarse: true, loop: ['跟随目标', '护卫'], text: '贴身保护' },
    { id: 'scout', acts: ['moveTo', 'observe'], name: '探查', module: 'military', fits: ['scout'], coarse: true, loop: ['抵近观察', '回报情报'], text: '把看到的写进己方情报库' },
    { id: 'trade', acts: ['withdraw', 'moveTo', 'exchange'], name: '贩运', module: 'diplomacy', fits: ['trade'], coarse: true, loop: ['装货', '赶路', '交易', '回程'], text: '商队往返' },
    { id: 'flee', acts: ['moveTo'], name: '逃跑', module: 'jobs', fits: ['*'], coarse: true, loop: ['察觉危险', '跑回城'], text: '非战斗职业遇险自动逃' },
    { id: 'idle', acts: ['wait'], name: '闲着', module: 'jobs', fits: ['idle', '*'], coarse: true, loop: ['原地等待'], text: '没活可干时的兜底' },
  ],

  // ------------------------------------------------------------------ 职业
  professions: [
    { id: 'farmer', name: '农夫', short: '农', color: '#84cc16', tags: ['worker'], status: 'draft',
      stats: { speed: 1.0, carry: 10, hp: 100, attack: 2 }, behaviors: ['farm', 'deliver', 'flee', 'idle'],
      defaultOrder: 'work: 粮食', tools: { 锄头: 1.4 }, upkeep: { 粮: 1 }, train: { cost: { 粮: 3 }, days: 1 },
      text: '在城镇附近的田里春种秋收，是全国的饭碗。冬天田里不产粮。' },
    { id: 'woodcutter', name: '伐木工', short: '木', color: '#d97706', tags: ['worker'], status: 'draft',
      stats: { speed: 1.0, carry: 10, hp: 100, attack: 3 }, behaviors: ['gather', 'deliver', 'flee', 'idle'],
      defaultOrder: 'work: 木头', tools: { 斧头: 1.5 }, upkeep: { 粮: 1 }, train: { cost: { 粮: 3 }, days: 1 },
      text: '去林区砍树，背满了送回仓库。木头是建造和兵器的基础。' },
    { id: 'mason', name: '石匠', short: '石', color: '#94a3b8', tags: ['worker'], status: 'draft',
      stats: { speed: 0.9, carry: 8, hp: 110, attack: 3 }, behaviors: ['gather', 'deliver', 'flee', 'idle'],
      defaultOrder: 'work: 石头', tools: { 镐: 1.4 }, upkeep: { 粮: 1 }, train: { cost: { 粮: 3 }, days: 1 },
      text: '采石，供城墙和大建筑用。' },
    { id: 'miner', name: '矿工', short: '矿', color: '#64748b', tags: ['worker'], status: 'draft',
      stats: { speed: 0.9, carry: 8, hp: 110, attack: 3 }, behaviors: ['gather', 'deliver', 'flee', 'idle'],
      defaultOrder: 'work: 铁', tools: { 镐: 1.3 }, upkeep: { 粮: 1.5 }, train: { cost: { 粮: 4 }, days: 2 },
      text: '挖铁矿。没有铁就没有兵器，铁矿点是兵家必争之地。' },
    { id: 'builder', name: '建筑工', short: '建', color: '#f59e0b', tags: ['worker'], status: 'draft',
      stats: { speed: 1.0, carry: 10, hp: 100, attack: 2 }, behaviors: ['build', 'haul', 'flee', 'idle'],
      defaultOrder: 'build: 队列里下一个工地', tools: { 锤子: 1.5 }, upkeep: { 粮: 1 }, train: { cost: { 粮: 3 }, days: 1 },
      text: '按诸侯的建造单从仓库取料去工地施工。' },
    { id: 'smith', name: '铁匠', short: '铁', color: '#ef4444', tags: ['worker'], status: 'draft',
      stats: { speed: 0.9, carry: 6, hp: 100, attack: 4 }, behaviors: ['craft', 'haul', 'idle'],
      defaultOrder: 'work: 兵器', tools: {}, upkeep: { 粮: 1 }, train: { cost: { 粮: 5 }, days: 3 },
      text: '在铁匠铺把铁和木头打成兵器和工具。' },
    { id: 'porter', name: '搬运工', short: '运', color: '#14b8a6', tags: ['worker'], status: 'draft',
      stats: { speed: 1.1, carry: 20, hp: 100, attack: 2 }, behaviors: ['haul', 'deliver', 'flee', 'idle'],
      defaultOrder: 'idle', tools: {}, upkeep: { 粮: 1 }, train: { cost: { 粮: 2 }, days: 1 },
      text: '在前哨和城镇之间运货。路上可能被劫。' },
    { id: 'soldier', name: '士兵', short: '兵', color: '#3b82f6', tags: ['military'], status: 'draft',
      stats: { speed: 1.1, carry: 5, hp: 150, attack: 12 }, behaviors: ['fight', 'guard', 'patrol', 'march', 'escort', 'idle'],
      defaultOrder: 'guard: 所属城镇', tools: { 兵器: 1.6 }, upkeep: { 粮: 1.5 }, train: { cost: { 粮: 5, 铁: 1 }, days: 2 },
      text: '驻守、巡逻、行军、攻城。吃得多，还要铁做兵器。' },
    { id: 'scout', name: '斥候', short: '斥', color: '#a855f7', tags: ['military'], status: 'draft',
      stats: { speed: 1.6, carry: 3, hp: 80, attack: 4 }, behaviors: ['scout', 'march', 'flee', 'idle'],
      defaultOrder: 'idle', tools: {}, upkeep: { 粮: 1 }, train: { cost: { 粮: 4 }, days: 2 },
      text: '跑得快。去别人地盘看兵力和粮草，写进己方情报库。' },
    { id: 'merchant', name: '商人', short: '商', color: '#eab308', tags: ['worker'], status: 'draft',
      stats: { speed: 1.0, carry: 30, hp: 90, attack: 2 }, behaviors: ['trade', 'haul', 'flee', 'idle'],
      defaultOrder: 'idle', tools: {}, upkeep: { 粮: 1 }, train: { cost: { 粮: 4, 金: 20 }, days: 2 },
      text: '带货去别的势力换东西。商路也是情报和冲突的来源。' },
  ],

  // ------------------------------------------------------------------ 选择器
  selectors: [
    { syntax: '@木 / @伐木工', meaning: '我所有的伐木工（职业简称或全称）' },
    { syntax: '@木@青石城', meaning: '青石城的伐木工' },
    { syntax: '@木:5', meaning: '5 个伐木工（优先空闲的、离得近的）' },
    { syntax: '@农:30%', meaning: '三成农夫' },
    { syntax: '@worker', meaning: '按标签选：所有干活的（worker / military）' },
    { syntax: '#一队', meaning: '已编好的队伍' },
    { syntax: '阿三', meaning: '指定某个人' },
    { syntax: '@木,@石', meaning: '多选：伐木工和石匠' },
    { syntax: '*@河口镇', meaning: '河口镇所有人' },
  ],

  // ------------------------------------------------------------------ 命令
  // args 类型：sel 选择器 · town 己方城镇 · place 地点 · target 势力.城镇/地区 · work 活 ·
  //           prof 职业 · item 物品 · building 建筑 · group 队名 · faction 势力 · notable 名人 ·
  //           int 整数 · amount 数量（粮200/300金） · duration 时长（30天） · treaty 条约 ·
  //           disaster 天灾 · quota 职业比例（余下全部） · text 文字（余下全部）
  // 参数名后面带 ? 表示可省略
  commands: [
    { id: 'quota', verb: '比例', module: 'jobs', who: ['lord'], args: [['城镇', 'town'], ['比例', 'quota']],
      help: '设城镇的职业比例，系统自动把空闲的人分配/转职过去（锁定的人不动）', examples: ['比例 青石城 农50 木20 石10 兵20'] },
    { id: 'assign', verb: '派', module: 'jobs', who: ['lord', 'god'], order: 'work', args: [['人', 'sel'], ['活', 'work'], ['地点?', 'place']],
      help: '把一批人派去干某种活；派出去的人会锁定，直到"放"', examples: ['派 @木:5 伐木 北林', '派 @农@河口镇 种田'] },
    { id: 'haul', verb: '运', module: 'jobs', who: ['lord'], order: 'haul', args: [['人', 'sel'], ['物品', 'item'], ['从', 'place'], ['到', 'place']],
      help: '让一批人在两地之间运货', examples: ['运 @运:4 木头 北林 青石城'] },
    { id: 'release', verb: '放', module: 'jobs', who: ['lord'], args: [['人', 'sel']],
      help: '解除锁定，还给职业比例自动分配', examples: ['放 @木@北林'] },
    { id: 'retrain', verb: '转', module: 'jobs', who: ['lord'], args: [['人', 'sel'], ['职业', 'prof']],
      help: '转职（要花粮食和时间，见职业数据）', examples: ['转 @农:10 兵'] },
    { id: 'group', verb: '编', module: 'jobs', who: ['lord'], args: [['人', 'sel'], ['队名', 'group']],
      help: '把一批人编成队伍，之后用 #队名 指挥', examples: ['编 @兵@青石城:20 一队'] },
    { id: 'build', verb: '建', module: 'building', who: ['lord'], order: 'build', args: [['建筑', 'building'], ['地点', 'place'], ['人?', 'sel']],
      help: '下建造单；不指定人就交给建筑工队列', examples: ['建 兵营 青石城', '建 城墙 河口镇 @建:6'] },
    { id: 'demolish', verb: '拆', module: 'building', who: ['lord'], args: [['建筑', 'building'], ['地点', 'place']],
      help: '拆掉建筑，退回部分材料', examples: ['拆 伐木场 北林'] },
    { id: 'attack', verb: '攻', module: 'military', who: ['lord'], order: 'attack', args: [['人', 'sel'], ['目标', 'target']],
      help: '进攻城镇、部队或地区（持续，直到撤回或打完）', examples: ['攻 #一队 赤焰.河口镇'] },
    { id: 'guard', verb: '守', module: 'military', who: ['lord'], order: 'guard', args: [['人', 'sel'], ['地点', 'place']],
      help: '驻守某地', examples: ['守 #二队 青石城'] },
    { id: 'patrol', verb: '巡', module: 'military', who: ['lord'], order: 'patrol', args: [['人', 'sel'], ['区域', 'place']],
      help: '在区域里巡逻', examples: ['巡 @兵:6 北林'] },
    { id: 'retreat', verb: '撤', module: 'military', who: ['lord'], order: 'move', args: [['人', 'sel'], ['地点?', 'place']],
      help: '撤回（不写地点就回所属城镇）', examples: ['撤 #一队'] },
    { id: 'scout', verb: '探', module: 'military', who: ['lord'], order: 'scout', args: [['人', 'sel'], ['区域', 'place']],
      help: '侦察某地，结果写进情报库', examples: ['探 @斥:2 东山'] },
    { id: 'escort', verb: '护', module: 'military', who: ['lord'], order: 'escort', args: [['人', 'sel'], ['对象', 'sel']],
      help: '护送某人或某队', examples: ['护 #三队 #商队'] },
    { id: 'trade', verb: '商', module: 'diplomacy', who: ['lord'], order: 'trade', args: [['人', 'sel'], ['对方', 'faction']],
      help: '派商队去某势力交易', examples: ['商 @商:2 白鹿'] },
    { id: 'tax', verb: '税', module: 'population', who: ['lord'], args: [['城镇', 'town'], ['税率', 'int']],
      help: '设税率（%）。税高民心降', examples: ['税 青石城 15'] },
    { id: 'granary', verb: '开仓', module: 'population', who: ['lord'], args: [['城镇', 'town'], ['粮', 'int']],
      help: '开仓放粮，提升民心', examples: ['开仓 河口镇 200'] },
    { id: 'recruit', verb: '招', module: 'population', who: ['lord'], args: [['名人', 'notable'], ['出价', 'amount']],
      help: '招揽或策反名人', examples: ['招 李将军 300金'] },
    { id: 'letter', verb: '信', module: 'diplomacy', who: ['lord'], args: [['对方', 'faction'], ['内容', 'text']],
      help: '私信，只有对方看得到（可以撒谎）', examples: ['信 赤焰 北林归你，河口归我，如何？'] },
    { id: 'proclaim', verb: '告', module: 'diplomacy', who: ['lord'], args: [['内容', 'text']],
      help: '公开宣告，所有诸侯都看得到', examples: ['告 赤焰背约在先，天下共讨之'] },
    { id: 'propose', verb: '约', module: 'diplomacy', who: ['lord'], args: [['对方', 'faction'], ['条约', 'treaty'], ['时长?', 'duration']],
      help: '提议条约', examples: ['约 赤焰 互不侵犯 30天'] },
    { id: 'accept', verb: '应', module: 'diplomacy', who: ['lord'], args: [['对方', 'faction']],
      help: '接受对方提议的条约', examples: ['应 赤焰'] },
    { id: 'break', verb: '撕', module: 'diplomacy', who: ['lord'], args: [['对方', 'faction'], ['条约', 'treaty']],
      help: '撕毁条约（会记进公开史册，影响声望）', examples: ['撕 赤焰 互不侵犯'] },
    { id: 'gift', verb: '赠', module: 'diplomacy', who: ['lord'], args: [['对方', 'faction'], ['东西', 'amount']],
      help: '送礼', examples: ['赠 白鹿 粮200'] },
    { id: 'think', verb: '想', module: 'ai', who: ['lord'], args: [['内容', 'text']],
      help: '心里话：写下计划和判断，只有上帝看得到，下次醒来时带上', examples: ['想 赤焰兵多粮少，拖到冬天再打'] },
    { id: 'disaster', verb: '灾', module: 'god', who: ['god'], args: [['天灾', 'disaster'], ['地点', 'place'], ['时长?', 'duration']],
      help: '降天灾：旱、涝、疫、蝗', examples: ['灾 旱 北林 10天'] },
    { id: 'bless', verb: '赐', module: 'god', who: ['god'], args: [['对方', 'faction'], ['东西', 'amount']],
      help: '天降资源', examples: ['赐 白鹿 铁100'] },
    { id: 'forge', verb: '冒名', module: 'god', who: ['god'], args: [['冒充谁', 'faction'], ['发给谁', 'faction'], ['内容', 'text']],
      help: '冒名给某诸侯写私信，对方分不出真假', examples: ['冒名 赤焰 白鹿 我军三日后借道'] },
    { id: 'dream', verb: '托梦', module: 'god', who: ['god'], args: [['对方', 'faction'], ['内容', 'text']],
      help: '以"上天"身份对某诸侯说话', examples: ['托梦 白鹿 东方有变'] },
    { id: 'bandits', verb: '寇', module: 'god', who: ['god'], args: [['地点', 'place'], ['人数', 'int']],
      help: '召唤流寇', examples: ['寇 东山 50'] },
    { id: 'speed', verb: '时速', module: 'god', who: ['god'], args: [['倍率', 'int']],
      help: '时间倍率（0 = 暂停）', examples: ['时速 4'] },
  ],

  // 命令试验台用的示例世界（只用来校验名字，不是真实存档）
  sampleWorld: {
    me: '青龙',
    factions: ['青龙', '赤焰', '白鹿', '玄武'],
    towns: { 青龙: ['青石城', '河口镇'], 赤焰: ['赤焰城', '河口镇'], 白鹿: ['鹿鸣城'], 玄武: ['北冥城'] },
    myTowns: ['青石城', '河口镇'],
    places: ['青石城', '河口镇', '北林', '东山', '南湖', '西岭', '赤焰城', '鹿鸣城', '北冥城'],
    groups: ['一队', '二队', '三队', '商队'],
    people: ['阿三', '阿四', '老王'],
    notables: ['李将军', '张谋士'],
    items: ['粮', '粮食', '木头', '石头', '铁', '金', '兵器', '工具'],
    works: { 伐木: 'woodcutter', 采石: 'mason', 挖矿: 'miner', 种田: 'farmer', 打铁: 'smith' },
    buildings: ['房屋', '农田', '伐木场', '采石场', '矿场', '仓库', '兵营', '铁匠铺', '市场', '城墙', '道路'],
    treaties: ['结盟', '互不侵犯', '朝贡', '通商', '借道'],
    disasters: ['旱', '涝', '疫', '蝗'],
  },

  // ------------------------------------------------------------------ 扩展指南
  recipes: [
    { id: 'profession', title: '加一个职业', steps: ['在 content/professions/ 加一份数据（属性、行为、默认命令、口粮、转职）', '跑 npm run atlas，图谱里自动出现'], note: '只有全新种类的活才需要写新行为。' },
    { id: 'item', title: '加一种建筑 / 物品', steps: ['在 content/buildings/ 或 content/items/ 加数据', '有特殊效果的话，在相关模块加一个系统'] },
    { id: 'command', title: '加一条命令', steps: ['在相关模块的 commands 里加一个 CommandDef（动词、参数、说明、例子）', '解析器、AI 命令表、上帝面板按钮、文档、契约测试自动跟上'] },
    { id: 'behavior', title: '加一种活 / 行为', steps: ['在相关模块加一个 BehaviorDef（fits / start / tick / coarse）', '在职业数据的 behaviors 里写上它的 ID'] },
    { id: 'briefing', title: 'AI 简报里多看一样东西', steps: ['在模块里加一个 BriefingSection（优先级 + 长度预算）'] },
    { id: 'module', title: '加一个全新玩法（比如"宗教"）', steps: ['npm run new:module religion 生成模板', '组件 → 系统 → 动作 → 命令 → 事件 → 简报 → 存档 → 配置', '前端加同名图层（如有画面）', '写测试', '在 src/game/index.ts 加一行'], note: '核心文件一个都不用改。' },
  ],

  // ------------------------------------------------------------------ 测试与守门
  gates: [
    { name: '模块单元测试', text: '每个模块自己的规则' },
    { name: '命令契约测试', text: '每条命令的每个例子都能真正执行成功' },
    { name: '可重现测试', text: '同种子 + 同命令，跑 N 个游戏日后状态哈希一致' },
    { name: '分层测试', text: '不许向上依赖、不许绕过模块公开接口' },
    { name: '存档测试', text: '存了再读一致；旧版本存档能迁移' },
    { name: '协议测试', text: '消息编码再解码一致' },
    { name: '压测预算', text: '10km 地图 + 2000 NPC，每节拍 < 5ms，超了就失败' },
    { name: '脚本 AI 长跑', text: '无人值守跑 N 年不崩、没有异常增长' },
    { name: '图谱校验', text: '本页面的数据引用完整、命令例子都能解析（已接入：npm run atlas）' },
  ],

  // ------------------------------------------------------------------ 路线图
  roadmap: [
    { stage: 0, name: '地基', status: 'wip', text: '骨架、测试运行器、固定节拍、地图生成、镜头缩放、色块渲染、压测', goal: '10km 大陆上 2000 个色块小人干活不卡' },
    { stage: 1, name: '经济', status: 'draft', text: '城镇、职业与工作循环、建筑、资源刷新、季节、吃饭与迁移、远处粗算', goal: '几座城自己运转，冬天会饿' },
    { stage: 2, name: '军事领土', status: 'draft', text: '征兵、部队、行军、围城、战斗结算、领地', goal: '脚本诸侯会打仗、换城' },
    { stage: 3, name: 'AI 诸侯', status: 'draft', text: '简报、命令、唤醒、模型接入、脚本 AI、日志', goal: '大模型诸侯自己经营和开战（关键验收点）' },
    { stage: 4, name: '外交信息', status: 'draft', text: '私信、宣告、条约、史册、声望、迷雾、名人、贸易', goal: '结盟、背叛、撒谎' },
    { stage: 5, name: '上帝模式', status: 'draft', text: '干预工具、心里话面板、关系图、时间控制', goal: '你能看戏和搅局' },
    { stage: 6, name: '无尽演化', status: 'draft', text: '起义、叛将自立、席位交接、存读档、长跑平衡', goal: '世界一直跑下去' },
  ],

  // ------------------------------------------------------------------ 待定
  decisions: [
    { q: '命令用中文动词还是英文？', proposal: '中文（内部 ID 英文）', status: 'open' },
    { q: '选择器符号 @职业 #队伍 :数量 :30% 可以吗？', proposal: '如上', status: 'open' },
    { q: '"比例 + 直接派会锁定"双模式可以吗？', proposal: '可以', status: 'open' },
    { q: 'AI 席位数', proposal: '4–6 位诸侯', status: 'open' },
    { q: '战斗观赏度', proposal: '第一版公式结算 + 简单动画', status: 'open' },
    { q: '时间节奏：1 天 ≈ 10 秒？', proposal: '是，可调', status: 'open' },
    { q: '游戏名', proposal: '暂名"诸侯争霸"', status: 'open' },
    { q: '新仓库 AGENTS.md 协作约定', proposal: '沿用旧仓库规矩并改写', status: 'open' },
    { q: '技术栈', proposal: 'TypeScript：网页画面 + 后端模拟', status: 'decided' },
    { q: '模型接入', proposal: '后端直接调用 OpenAI 兼容接口 + 脚本 AI', status: 'decided' },
  ],
};
